version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=slowlycard
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
